apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - local.yaml

replacements:
  - source:
      fieldPath: data.image
      kind: ConfigMap
      name: m-ai-local-config
    targets:
      - fieldPaths:
          - spec.template.spec.containers.[name=daemon].image
          - spec.template.spec.containers.[name=daemon].env.[name=M_AI_IMAGE].value
        select:
          kind: Deployment
          name: m-ai-daemon
  - source:
      fieldPath: data.mainPlayer
      kind: ConfigMap
      name: m-ai-local-config
    targets:
      - fieldPaths:
          - spec.template.spec.containers.[name=daemon].env.[name=MAIN_PLAYER].value
        select:
          kind: Deployment
          name: m-ai-daemon
