{
 "title": "Minecraft",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chest 0 Tools",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_chest_stone_pickaxe_count{chestIndex=\"0\"}",
     "legendFormat": "Pick Axes (chest {{chestIndex}})"
    },
    {
     "expr": "minecraft_chest_stone_shovel_count{chestIndex=\"0\"}",
     "legendFormat": "Shovels (chest {{chestIndex}})"
    },
    {
     "expr": "minecraft_chest_minion{chestIndex=\"0\"}",
     "legendFormat": "Minion Number"
    }
   ]
  },
  {
   "title": "Chest 1 Tools",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_chest_stone_pickaxe_count{chestIndex=\"1\"}",
     "legendFormat": "Pick Axes (chest {{chestIndex}})"
    },
    {
     "expr": "minecraft_chest_stone_shovel_count{chestIndex=\"1\"}",
     "legendFormat": "Shovels (chest {{chestIndex}})"
    },
    {
     "expr": "minecraft_chest_minion{chestIndex=\"1\"}",
     "legendFormat": "Minion Number"
    }
   ]
  },
  {
   "title": "Current users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(minecraft_log_level)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Torches",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_item_torch, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Stone Pickaxes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_item_stone_pickaxes, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Current Health",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_user_health, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Position X",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_user_x, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_user_y, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Position Z",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_user_z, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Add Torches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_user_add_torches == 1, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Dig Millis",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(minecraft_dig_millis, \"userName\")",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Mining",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "targets": [
    { "expr": "minecraft_is_mining == 1", "legendFormat": "{{userName}}" }
   ]
  },
  {
   "title": "Unused minions",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    { "expr": "minecraft_no_goal == 1", "legendFormat": "{{userName}}" }
   ]
  },
  {
   "title": "Log Level",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minecraft_log_level", "legendFormat": "{{userName}}" }
   ]
  }
 ]
}