apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: m-ai-daemon
  name: m-ai-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-ai-daemon
  template:
    metadata:
      labels:
        app: m-ai-daemon
    spec:
      serviceAccountName: m-ai-daemon
      containers:
        - args:
            - daemon
            - start
          env:
            - name: STORAGE_REDIS_HOST
              value: redis:6379
            - name: MAIN_PLAYER
              value: unset
            - name: M_AI_BOT_RUNNER
              value: kubernetes
            - name: M_AI_IMAGE
              value: registry.invalid/m-ai:latest
            - name: NODE_EXTRA_CA_CERTS
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          image: registry.invalid/m-ai:latest
          imagePullPolicy: Always
          name: daemon
          ports:
            - containerPort: 50000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m-ai-daemon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: m-ai-daemon
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: m-ai-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: m-ai-daemon
subjects:
  - kind: ServiceAccount
    name: m-ai-daemon
---
apiVersion: v1
kind: Service
metadata:
  name: m-ai-daemon
spec:
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: m-ai-daemon
