apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daemon.yaml
  - prometheus.yaml
  - grafana.yaml
  - loki.yaml
  - minecraft.yaml
  - postgres.yaml
  - storage.yaml

configMapGenerator:
  - name: grafana-dashboards
    namespace: observability
    files:
      - grafana-dashboard.json
      - gameplay-dashboard.json
  - name: pgadmin-servers
    files:
      - pgadmin-servers.json
