apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daemon.yaml
  - prometheus.yaml
  - grafana.yaml
  - minecraft.yaml
  - redis.yaml
  - storage.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - grafana-dashboard.json
