apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minecraft
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k3s-pv"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: function
              operator: In
              values:
                - minecraft-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minecraft
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
