apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
    m-ai/storage: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k3s-prometheus"
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: m-ai/observability
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minecraft
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k3s-pv"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: m-ai/minecraft-server
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-loki
  labels:
    m-ai/observability: "true"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k3s-loki"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: m-ai/observability
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: observability
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      m-ai/observability: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minecraft
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      m-ai/minecraft-db: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    m-ai/minecraft-db: "true"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k3s-postgres"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: m-ai/minecraft-db
              operator: In
              values:
                - "true"
